name: prestashop
services:
  prestashop:
    image: ${PRESTASHOP_IMAGE}
    container_name: ${PRESTASHOP_CONTAINER_NAME}
    env_file:
      - .env
    ports:
      - ${PRESTASHOP_PORT}:80
    volumes:
      - ./prestashop/logs:/var/log/apache2
    #   - ./prestashop/modules:/var/www/html/modules
    #   - ./prestashop/themes:/var/www/html/themes
    environment:
      DB_SERVER: mysql
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASSWD: ${MYSQL_PASSWORD}
      PS_ENABLE_SSL: 0
      PS_DOMAIN: ${PRESTASHOP_HOST}:${PRESTASHOP_PORT}
      PS_INSTALL_AUTO: 1
      PS_FOLDER_ADMIN: ${PS_FOLDER_ADMIN}
      PS_FOLDER_INSTALL: ${PS_FOLDER_INSTALL}
      APACHE_LOG_DIR: /var/log/apache2
      ADMIN_MAIL: ${ADMIN_MAIL}
      ADMIN_PASSWD: ${ADMIN_PASSWD}
    links:
      - mysql
    depends_on:
      - mysql
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '1gb'
        reservations:
          cpus: '0.1'
          memory: '50mb'
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  mysql:
    image: ${MYSQL_IMAGE}
    container_name: ${MYSQL_CONTAINER_NAME}
    env_file:
      - .env
    restart: no
    volumes:
      - ./mysql/config:/etc/mysql/conf.d
      - ./mysql/logs:/var/log/mysql
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_INITDB_SKIP_TZINFO: 1
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '1gb'
        reservations:
          cpus: '0.1'
          memory: '50mb'
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
