name: 'odoo-local'
services:
  db:
    image: postgres:14.15
    container_name: odoo-database
    restart: no
    volumes:
      - ./postgresql/logs:/var/log/postgresql
      - ./postgresql/postgresql.conf:/etc/postgresql/postgresql.conf
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: postgres
    command: "-c 'config_file=/etc/postgresql/postgresql.conf'"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: '2.5gb'
        reservations:
          cpus: '0.25'
          memory: '20mb'
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
    ports:
      - ${POSTGRES_PORT}:5432

  app:
    image: odoo:17.0
    container_name: odoo-app
    restart: no
    volumes:
      - ./odoo/extra-addons:/mnt/extra-addons
      - ./odoo/enterprise-addons:/mnt/enterprise-addons
      - ./odoo/logs:/var/log/odoo
      - ./odoo/config:/etc/odoo
    env_file:
      - .env
    environment:
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
      PASSWORD: ${POSTGRES_PASSWORD}
      USER: ${POSTGRES_USER}
      PORT: ${POSTGRES_PORT}
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: '2gb'
        reservations:
          cpus: '0.25'
          memory: '20mb'
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
    depends_on:
      - db
    links:
      - db
    ports:
      - ${ODOO_XMLRPC_PORT}:8069
      - ${ODOO_LONG_POLLING_PORT}:8072
